aws:
  region: eu-central-1
  account_id: 333333333333
s3:
  raw_bucket: ml-prod-raw-data
  features_bucket: ml-prod-features
  artifacts_bucket: ml-prod-artifacts
  monitoring_bucket: ml-prod-monitoring
ecr:
  registry: 333333333333.dkr.ecr.eu-central-1.amazonaws.com
  repo: ml-inference
sagemaker:
  role_arn: arn:aws:iam::333333333333:role/SageMakerExecutionRole
  instance_type: ml.m5.large
mlflow:
  tracking_uri: https://mlflow.prod.example.com
  experiment_name: my-experiment-prod
bedrock:
  model_id: anthropic.claude-3-sonnet
  max_tokens: 4096
model:
  name: my-model
  version: latest
  canary_traffic: 0.05
  health_check_path: /health
monitoring:
  sample_rate: 0.05
  drift_threshold: 0.05
  latency_threshold_ms: 500
  error_rate_threshold: 0.02
cost:
  monthly_budget_usd: 10000
  per_inference_limit_usd: 0.10
logging:
  level: WARNING
  cloudwatch_group: /aws/ml/prod
