name: Build and Push
on:
  push:
    branches: [develop, main]
  workflow_dispatch:
env:
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPO: ${{ secrets.ECR_REPO }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.CI_ASSUME_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build training image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:train-${{ github.sha }} -f Dockerfile.train .
      - name: Build inference image
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPO:inference-${{ github.sha }} -f Dockerfile.inference .
      - name: Run container security scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image $ECR_REGISTRY/$ECR_REPO:inference-${{ github.sha }}
      - name: Push images
        run: |
          docker push $ECR_REGISTRY/$ECR_REPO:train-${{ github.sha }}
          docker push $ECR_REGISTRY/$ECR_REPO:inference-${{ github.sha }}
      - name: Tag as latest for main branch
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag $ECR_REGISTRY/$ECR_REPO:inference-${{ github.sha }} $ECR_REGISTRY/$ECR_REPO:inference-latest
          docker push $ECR_REGISTRY/$ECR_REPO:inference-latest
